---
- name: Stopping Non-root services
  hosts: remote
  gather_facts: no  # Disable fact gathering at the master level if not needed
  become: yes

  tasks:
    - command: service --status-all
      name: Get list of running services
      register: running_services
    - name: Stop non-root user services
      shell: >
        for service in $(echo "{{ running_services.stdout }}" | grep running |
        awk '{print $1}'); do
         if ! grep -q 'root' /etc/init.d/$service; then
         service $service stop
        fi

        done
      when: running_services.stdout is defined
