---
- name: Configure webservers
  hosts: webservers
  gather_facts: yes
  tasks:
    - name: Install web server
      yum:
        name: httpd
        state: present

    - name: Start web server
      service:
        name: httpd
        state: started

